### PR TITLE
fix: Remove log4j v1 jars from hive CLASSPATH

### LINKED ISSUE #835: Hive: Log4j version and CLASSPATH
Hive uses log4j2 logger, but log4j v1 jars are also included in its CLASSPATH. 
This generates errors when configuring log4j for ranger plugin auditlogs

Log4j v1 jars are included by the following line in `hive-env.sh.j2` template :
~~~
export AUX_CLASSPATH="{{ tez_install_dir }}/*:{{ tez_install_dir }}/lib/*"
~~~
- Including `*` in the CLASSPATH is considered bad practice.
- log4j jars from tez should not be included in hive CLASSPATH

 `hive-env.sh.j2` ansible template should be fixed to remove wildcards from hive `CLASSPATH` and filter out log4j jars when including `tez` jars

### PR DESCRIPTION
**Pull request by giem-git**
#### Which issue(s) this PR fixes

Fixes #835

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

File: roles/hive/common/templates/hive-env.sh.j2 [hunk 1]
```diff
@@ -45,7 +45,16 @@
...
+
+export AUX_CLASSPATH=""
+for f in {{ tez_install_dir }}/*.jar {{ tez_install_dir }}/lib/*.jar; do
+  if [[ $f != *"log4j"* ]]; then
+    AUX_CLASSPATH=${AUX_CLASSPATH}:$f;
+  fi
+done
+
+
+
```
Comment (rpignolet) [inline roles/hive/common/templates/hive-env.sh.j2:57]: Why so many newlines ?

**Review by mehdibn — APPROVED** [review]

File: roles/hive/common/templates/hive-env.sh.j2 (hunk 1 above)
Comment (giem-git) [reply roles/hive/common/templates/hive-env.sh.j2]: Ooops ! No reason. One will be enough

**Review by rpignolet — APPROVED** [review]
